/*************************************************************************************************************
 * @name			FieldReportConstants
 * @author			Martín De León
 * @created			11 / 01 / 2025
 * @description		Class to hold constants for the project
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 * 				No.		Date			Author					Description
 * 				----	------------	--------------------	----------------------------------------------
 * @version		1.0		2025-01-11		Martín De León			Initialized class
 *
**************************************************************************************************************/
public with sharing class FieldReportConstants {

    public static final String CUSTOM_OBJECT_SUFIX = 'c';
    public static final String HISTORY_OBJECT_SUFIX = 'History';


}